### ISSUE TITLE
[Feat Request]Laravel Sail

### ISSUE THREAD

**Issue by SHJordan** [thinkverse/surf#12]
**Is your feature request related to a problem? Please describe.**
Yes. Please implement a solution for using surf with laravel sail container enviroment.

**Describe the solution you'd like**
Docs for installing the required package can be found here: https://laravel.com/docs/9.x/sail#installing-sail-into-existing-applications

**Describe alternatives you've considered**
It would be nice to have alternative solutions, like laradock.

**Comment by thinkverse** [comment]
Surf already has required `laravel/sail` in dev. Surf also has all the docker files that [Wave](https://github.com/thedevdojo/wave) has. I haven't tested to see if it works correctly though. If you try it and it doesn't work I'd love a PR for a fix. 🙂

https://github.com/thinkverse/surf/blob/3f4321712a823072e5583b35a2bc7ee33e858114/composer.json#L29 

I am closing this issue since the feature already exists.
